#!/usr/bin/env node

'use strict';
const { exec, execSync } = require('child_process');

// Clean the bundle
execSync('rm -rf test/bundle');

// Lint the sources
try {
  execSync('npm run lint', { stdio: 'inherit' });
} catch (e) {
  error('Lint failed, operation aborted.');
}

// Compile the sources and watch them
const tsc = exec('npx tsc -w --project test/tsconfig.json');
tsc.stdout.on('data', data => console.log(String(data)));
tsc.stderr.on('data', data => {
  console.error(String(data));
  error('Build failed, operation aborted.');
});

// Run the local test server
const server = exec('npx live-server --watch=test --open="test/index.html?param=the%20value"');
server.stdout.on('data', data => console.log(String(data)));
server.stderr.on('data', data => error(String(data)));
server.on('close', code => {
  tsc.kill();
  process.exit(code);
});

// Error function
function error(message) {
  console.error('\x1b[41m%s\x1b[0m', message, '\n');
  process.exit(1);
}